# Cấu hình Proxy nội bộ
server {
    listen 80;
    server_name local.caulongshop.com;

    location /data/ {
        # Trỏ về IP của File Server
        proxy_pass http://192.168.20.101/; 
        allow 10.0.0.0/8;
        deny all;
    }
}
